name: notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  path_provider: ^2.1.5
  popover: ^0.3.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8

flutter:
  uses-material-design: true
